version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    reviewers:
      - "asadali214"
